mex -largeArrayDims -DLAPACKINDEX=mwSignedIndex CFLAGS='-O3 -DUSE_COL_MAJOR -std=c99 -D_GNU_SOURCE -pthread -m64 -fexceptions -D_FILE_OFFSET_BITS=64' apLocalFunctionsMex.c -lmwblas
mex -largeArrayDims -DLAPACKINDEX=mwSignedIndex CFLAGS='-O3 -DUSE_COL_MAJOR -std=c99 -D_GNU_SOURCE -pthread -m64 -fexceptions -D_FILE_OFFSET_BITS=64' apLocalGradientsMex.c -lmwblas
mex -largeArrayDims -DLAPACKINDEX=mwSignedIndex CFLAGS='-O3 -DUSE_COL_MAJOR -std=c99 -D_GNU_SOURCE -pthread -m64 -fexceptions -D_FILE_OFFSET_BITS=64' apLocalHessiansMex.c -lmwblas
mex -largeArrayDims -DLAPACKINDEX=mwSignedIndex CFLAGS='-O3 -DUSE_COL_MAJOR -std=c99 -D_GNU_SOURCE -pthread -m64 -fexceptions -D_FILE_OFFSET_BITS=64' apGlobalFunctionsMex.c -lmwblas
mex -largeArrayDims -DLAPACKINDEX=mwSignedIndex CFLAGS='-O3 -DUSE_COL_MAJOR -std=c99 -D_GNU_SOURCE -pthread -m64 -fexceptions -D_FILE_OFFSET_BITS=64' apGlobalGradientsMex.c -lmwblas
mex -largeArrayDims -DLAPACKINDEX=mwSignedIndex CFLAGS='-O3 -DUSE_COL_MAJOR -std=c99 -D_GNU_SOURCE -pthread -m64 -fexceptions -D_FILE_OFFSET_BITS=64' apGlobalHessiansMex.c -lmwblas
mex -largeArrayDims -DLAPACKINDEX=mwSignedIndex CFLAGS='-O3 -DUSE_COL_MAJOR -std=c99 -D_GNU_SOURCE -pthread -m64 -fexceptions -D_FILE_OFFSET_BITS=64' apGlobalMapsMex.c -lmwblas
mex -largeArrayDims -DLAPACKINDEX=mwSignedIndex CFLAGS='-O3 -DUSE_COL_MAJOR -std=c99 -D_GNU_SOURCE -pthread -m64 -fexceptions -D_FILE_OFFSET_BITS=64' apMatrixMassMex.c -lmwblas
mex -largeArrayDims -DLAPACKINDEX=mwSignedIndex CFLAGS='-O3 -DUSE_COL_MAJOR -std=c99 -D_GNU_SOURCE -pthread -m64 -fexceptions -D_FILE_OFFSET_BITS=64' apMatrixStiffnessMex.c -lmwblas
mex -largeArrayDims -DLAPACKINDEX=mwSignedIndex CFLAGS='-O3 -DUSE_COL_MAJOR -std=c99 -D_GNU_SOURCE -pthread -m64 -fexceptions -D_FILE_OFFSET_BITS=64' apMatrixBetaplaneMex.c -lmwblas
mex -largeArrayDims -DLAPACKINDEX=mwSignedIndex CFLAGS='-O3 -DUSE_COL_MAJOR -std=c99 -D_GNU_SOURCE -pthread -m64 -fexceptions -D_FILE_OFFSET_BITS=64' apMatrixBiharmonicMex.c -lmwblas