% Build file for MEX files.
mexFiles = {'apRefValuesMex.c'        , 'apRefGradientsMex.c',               ...
            'apRefHessiansMex.c'      , 'apPhysicalValuesMex.c',             ...
            'apPhysicalGradientsMex.c', 'apPhysicalHessiansMex.c',           ...
            'apPhysicalMapsMex.c'     , 'apMatrixMassMex.c',                 ...
            'apMatrixStiffnessMex.c'  , 'apMatrixBetaplaneMex.c',            ...
            'apMatrixBiharmonicMex.c'};

for i=1:length(mexFiles)
    file = ['./ap/mex/' mexFiles{i}];
    mex(['-I', matlabroot '/extern/include/'], ['-I' './ap/mex/'],           ...
        ['-I' './ap/numeric/'], '-DLAPACKINDEX=mwSignedIndex',               ...
        '-DUSE_COL_MAJOR', '-DMWINDEX=mwIndex', ['CFLAGS=\'                  ...
        '$CFLAGS -fPIC -O3 -std=c99'], 'LDFLAGS=\$LDFLAGS', '-lmwblas',      ...
        '-largeArrayDims', file);
end
